name: Deploy flask application to VM
on:
  push:
    branches:
      - "ic-devops-batch-03"

env:
  DEPLOYMENT_SERVER_IP: ${{ secrets.INSTANCE_IP }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout git repository
        uses: actions/checkout@v4
      
      - name: Create deployment package
        
        run: |
          tar -czf deploy.tar.gz \
          --exclude=".git" \
          --exclude=".pyc" \
          --exclude="__pycache__" \
          --exclude="deploy.tar.gz" \
          --warning=no-file-changed \
          api
      - name: Transfer deploy archive file to VM
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ env.DEPLOYMENT_SERVER_IP }}
          username: ubuntu
          key: ${{ secrets.INSTANCE_RSA_PRIVATE_KEY }}
          source: "deploy.tar.gz"
          target: "~/"

      # - name: Deploy mycoolwebapp package to VM
      #   uses: appleboy/ssh-action@v1.2.0
      #   with:
      #     host: ${{ env.DEPLOYMENT_SERVER_IP }}
      #     username: ubuntu
      #     key: ${{ secrets.INSTANCE_RSA_PRIVATE_KEY }}
      #     script: |
      #       export COMMIT_HASH=$(echo ${{ github.sha }} | cut -c1-7)
      #       docker compose -f docker-compose.production.yaml up -d

